# Arithmatic Operations

In [1]:
import pandas as pd

In [2]:
dict={"A":[1,2,3,4], "B":[5,6,7,8]}
var=pd.DataFrame(dict)
var

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [7]:
var["C"]=var["A"]+var["B"]
var["D"]=var["A"]-var["B"]
var["E"]=var["A"]*var["B"]
var["F"]=var["A"]/var["B"]
var["G"]=var["E"]>20
var

   A  B   C  D   E         F      G
0  1  5   6 -4   5  0.200000  False
1  2  6   8 -4  12  0.333333  False
2  3  7  10 -4  21  0.428571   True
3  4  8  12 -4  32  0.500000   True

# Insert

In [16]:
var=pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10],"C":[11,12,13,14,15]})
var

   A   B   C
0  1   6  11
1  2   7  12
2  3   8  13
3  4   9  14
4  5  10  15

In [17]:
var.insert(1,"T",['a','b','c','d','e'])
var

   A  T   B   C
0  1  a   6  11
1  2  b   7  12
2  3  c   8  13
3  4  d   9  14
4  5  e  10  15

In [18]:
var['Test']=var["A"][0:3]
var

   A  T   B   C  Test
0  1  a   6  11   1.0
1  2  b   7  12   2.0
2  3  c   8  13   3.0
3  4  d   9  14   NaN
4  5  e  10  15   NaN

# Delete

In [19]:
var

   A  T   B   C  Test
0  1  a   6  11   1.0
1  2  b   7  12   2.0
2  3  c   8  13   3.0
3  4  d   9  14   NaN
4  5  e  10  15   NaN

In [20]:
var.pop("Test")
var

   A  T   B   C
0  1  a   6  11
1  2  b   7  12
2  3  c   8  13
3  4  d   9  14
4  5  e  10  15

In [21]:
del var["T"]
var

   A   B   C
0  1   6  11
1  2   7  12
2  3   8  13
3  4   9  14
4  5  10  15