# dropna & fillna

In [1]:
import pandas as pd

In [2]:
csv=pd.read_csv("sample.csv")
csv

   SYMBOL          SECURITY  TODAY-VOLUME  AVG.VOLUME  CHANGE
0     AAA        Alpha Corp      152300.0    140000.0    1.25
1     AAC         Gamma Inc       98500.0    102000.0    0.45
2     AAD         Delta PLC      305000.0    280000.0    2.15
3     AAE       Epsilon Ltd      120400.0         NaN   -1.05
4     AAF         Zeta Corp       87600.0     90000.0    0.75
5     AAG           Eta Inc       65400.0     70000.0   -0.55
6     AAH         Theta Ltd      450000.0    420000.0    3.25
7     AAI         Iota Corp      132000.0    128000.0    0.95
8     AAJ         Kappa Ltd           NaN     80000.0   -0.35
9     AAK        Lambda Inc       54000.0     60000.0   -1.25
10    AAL           Mu Corp      221000.0    200000.0    1.75
11    AAM            Nu Ltd      310000.0    295000.0    2.05
12    AAN            Xi Inc      112000.0    120000.0   -0.65
13    AAO      Omicron Corp       99000.0     95000.0    0.55
14    AAP            Pi Ltd      185000.0    170000.0    1.45
15    AAQ           Rho Inc       76000.0     78000.0   -0.25
16    AAR        Sigma Corp      143000.0    135000.0    0.85
17    AAS           Tau Ltd      204000.0    210000.0   -0.95
18    AAT       Upsilon Inc      178000.0         NaN    1.15
19    AAU          Phi Corp       89000.0     92000.0   -0.45
20    AAV           Chi Ltd      134000.0    130000.0    0.65
21    AAW           Psi Inc       67000.0     70000.0   -0.75
22    AAX        Omega Corp       45000.0     48000.0   -1.15
23    AAY     AlphaBeta Ltd      250000.0    230000.0    2.25
24    AAZ    GammaDelta Inc       99000.0    100000.0   -0.05
25    ABA  EpsilonZeta Corp      175000.0    160000.0    1.35
26    ABB      EtaTheta Ltd       88000.0     90000.0   -0.55
27    ABC     IotaKappa Inc      143500.0    140000.0    0.95
28    ABD     LambdaMu Corp      212000.0    200000.0    1.65
29    ABE          NuXi Ltd       66000.0     70000.0   -0.85
30    ABF     OmicronPi Inc           NaN    150000.0    0.55
31    ABG     RhoSigma Corp       87000.0     92000.0   -1.05
32    ABH    TauUpsilon Ltd       96000.0     94000.0    0.75
33    ABI        PhiChi Inc      118000.0    115000.0     NaN
34    ABJ     PsiOmega Corp      223000.0    210000.0    1.95
35    ABK      AlphaOne Ltd      178000.0    165000.0    1.25
36    ABL       BetaTwo Inc      134000.0    140000.0   -0.65
37    ABM   GammaThree Corp      198000.0    185000.0    1.55
38    ABN     DeltaFour Ltd       88000.0     92000.0   -0.95
39    ABO   EpsilonFive Inc       74000.0     76000.0   -0.35
40    ABP      ZetaSix Corp      120000.0    110000.0    1.05
41    ABQ      EtaSeven Ltd       99000.0    102000.0   -0.25
42    ABR    ThetaEight Inc       65000.0     70000.0     NaN
43    ABS     IotaNine Corp      205000.0    190000.0    2.05
44    ABT      KappaTen Ltd       87000.0     86000.0    0.35
45    ABU  LambdaEleven Inc      132000.0    125000.0    0.85
46    ABV     MuTwelve Corp      143000.0    150000.0   -0.75
47    ABW    NuThirteen Ltd           NaN     95000.0    0.55
48    ABX    XiFourteen Inc      158000.0    140000.0    1.75

In [3]:
# drop by rows
csv.dropna()

   SYMBOL          SECURITY  TODAY-VOLUME  AVG.VOLUME  CHANGE
0     AAA        Alpha Corp      152300.0    140000.0    1.25
1     AAC         Gamma Inc       98500.0    102000.0    0.45
2     AAD         Delta PLC      305000.0    280000.0    2.15
4     AAF         Zeta Corp       87600.0     90000.0    0.75
5     AAG           Eta Inc       65400.0     70000.0   -0.55
6     AAH         Theta Ltd      450000.0    420000.0    3.25
7     AAI         Iota Corp      132000.0    128000.0    0.95
9     AAK        Lambda Inc       54000.0     60000.0   -1.25
10    AAL           Mu Corp      221000.0    200000.0    1.75
11    AAM            Nu Ltd      310000.0    295000.0    2.05
12    AAN            Xi Inc      112000.0    120000.0   -0.65
13    AAO      Omicron Corp       99000.0     95000.0    0.55
14    AAP            Pi Ltd      185000.0    170000.0    1.45
15    AAQ           Rho Inc       76000.0     78000.0   -0.25
16    AAR        Sigma Corp      143000.0    135000.0    0.85
17    AAS           Tau Ltd      204000.0    210000.0   -0.95
19    AAU          Phi Corp       89000.0     92000.0   -0.45
20    AAV           Chi Ltd      134000.0    130000.0    0.65
21    AAW           Psi Inc       67000.0     70000.0   -0.75
22    AAX        Omega Corp       45000.0     48000.0   -1.15
23    AAY     AlphaBeta Ltd      250000.0    230000.0    2.25
24    AAZ    GammaDelta Inc       99000.0    100000.0   -0.05
25    ABA  EpsilonZeta Corp      175000.0    160000.0    1.35
26    ABB      EtaTheta Ltd       88000.0     90000.0   -0.55
27    ABC     IotaKappa Inc      143500.0    140000.0    0.95
28    ABD     LambdaMu Corp      212000.0    200000.0    1.65
29    ABE          NuXi Ltd       66000.0     70000.0   -0.85
31    ABG     RhoSigma Corp       87000.0     92000.0   -1.05
32    ABH    TauUpsilon Ltd       96000.0     94000.0    0.75
34    ABJ     PsiOmega Corp      223000.0    210000.0    1.95
35    ABK      AlphaOne Ltd      178000.0    165000.0    1.25
36    ABL       BetaTwo Inc      134000.0    140000.0   -0.65
37    ABM   GammaThree Corp      198000.0    185000.0    1.55
38    ABN     DeltaFour Ltd       88000.0     92000.0   -0.95
39    ABO   EpsilonFive Inc       74000.0     76000.0   -0.35
40    ABP      ZetaSix Corp      120000.0    110000.0    1.05
41    ABQ      EtaSeven Ltd       99000.0    102000.0   -0.25
43    ABS     IotaNine Corp      205000.0    190000.0    2.05
44    ABT      KappaTen Ltd       87000.0     86000.0    0.35
45    ABU  LambdaEleven Inc      132000.0    125000.0    0.85
46    ABV     MuTwelve Corp      143000.0    150000.0   -0.75
48    ABX    XiFourteen Inc      158000.0    140000.0    1.75

In [4]:
# subset: remove entire row if given column has null value
csv.dropna(subset=["CHANGE"])

   SYMBOL          SECURITY  TODAY-VOLUME  AVG.VOLUME  CHANGE
0     AAA        Alpha Corp      152300.0    140000.0    1.25
1     AAC         Gamma Inc       98500.0    102000.0    0.45
2     AAD         Delta PLC      305000.0    280000.0    2.15
3     AAE       Epsilon Ltd      120400.0         NaN   -1.05
4     AAF         Zeta Corp       87600.0     90000.0    0.75
5     AAG           Eta Inc       65400.0     70000.0   -0.55
6     AAH         Theta Ltd      450000.0    420000.0    3.25
7     AAI         Iota Corp      132000.0    128000.0    0.95
8     AAJ         Kappa Ltd           NaN     80000.0   -0.35
9     AAK        Lambda Inc       54000.0     60000.0   -1.25
10    AAL           Mu Corp      221000.0    200000.0    1.75
11    AAM            Nu Ltd      310000.0    295000.0    2.05
12    AAN            Xi Inc      112000.0    120000.0   -0.65
13    AAO      Omicron Corp       99000.0     95000.0    0.55
14    AAP            Pi Ltd      185000.0    170000.0    1.45
15    AAQ           Rho Inc       76000.0     78000.0   -0.25
16    AAR        Sigma Corp      143000.0    135000.0    0.85
17    AAS           Tau Ltd      204000.0    210000.0   -0.95
18    AAT       Upsilon Inc      178000.0         NaN    1.15
19    AAU          Phi Corp       89000.0     92000.0   -0.45
20    AAV           Chi Ltd      134000.0    130000.0    0.65
21    AAW           Psi Inc       67000.0     70000.0   -0.75
22    AAX        Omega Corp       45000.0     48000.0   -1.15
23    AAY     AlphaBeta Ltd      250000.0    230000.0    2.25
24    AAZ    GammaDelta Inc       99000.0    100000.0   -0.05
25    ABA  EpsilonZeta Corp      175000.0    160000.0    1.35
26    ABB      EtaTheta Ltd       88000.0     90000.0   -0.55
27    ABC     IotaKappa Inc      143500.0    140000.0    0.95
28    ABD     LambdaMu Corp      212000.0    200000.0    1.65
29    ABE          NuXi Ltd       66000.0     70000.0   -0.85
30    ABF     OmicronPi Inc           NaN    150000.0    0.55
31    ABG     RhoSigma Corp       87000.0     92000.0   -1.05
32    ABH    TauUpsilon Ltd       96000.0     94000.0    0.75
34    ABJ     PsiOmega Corp      223000.0    210000.0    1.95
35    ABK      AlphaOne Ltd      178000.0    165000.0    1.25
36    ABL       BetaTwo Inc      134000.0    140000.0   -0.65
37    ABM   GammaThree Corp      198000.0    185000.0    1.55
38    ABN     DeltaFour Ltd       88000.0     92000.0   -0.95
39    ABO   EpsilonFive Inc       74000.0     76000.0   -0.35
40    ABP      ZetaSix Corp      120000.0    110000.0    1.05
41    ABQ      EtaSeven Ltd       99000.0    102000.0   -0.25
43    ABS     IotaNine Corp      205000.0    190000.0    2.05
44    ABT      KappaTen Ltd       87000.0     86000.0    0.35
45    ABU  LambdaEleven Inc      132000.0    125000.0    0.85
46    ABV     MuTwelve Corp      143000.0    150000.0   -0.75
47    ABW    NuThirteen Ltd           NaN     95000.0    0.55
48    ABX    XiFourteen Inc      158000.0    140000.0    1.75

In [5]:
var=pd.read_csv("sample.csv")
var.fillna("ASDASD")

   SYMBOL          SECURITY TODAY-VOLUME AVG.VOLUME  CHANGE
0     AAA        Alpha Corp     152300.0   140000.0    1.25
1     AAC         Gamma Inc      98500.0   102000.0    0.45
2     AAD         Delta PLC     305000.0   280000.0    2.15
3     AAE       Epsilon Ltd     120400.0     ASDASD   -1.05
4     AAF         Zeta Corp      87600.0    90000.0    0.75
5     AAG           Eta Inc      65400.0    70000.0   -0.55
6     AAH         Theta Ltd     450000.0   420000.0    3.25
7     AAI         Iota Corp     132000.0   128000.0    0.95
8     AAJ         Kappa Ltd       ASDASD    80000.0   -0.35
9     AAK        Lambda Inc      54000.0    60000.0   -1.25
10    AAL           Mu Corp     221000.0   200000.0    1.75
11    AAM            Nu Ltd     310000.0   295000.0    2.05
12    AAN            Xi Inc     112000.0   120000.0   -0.65
13    AAO      Omicron Corp      99000.0    95000.0    0.55
14    AAP            Pi Ltd     185000.0   170000.0    1.45
15    AAQ           Rho Inc      76000.0    78000.0   -0.25
16    AAR        Sigma Corp     143000.0   135000.0    0.85
17    AAS           Tau Ltd     204000.0   210000.0   -0.95
18    AAT       Upsilon Inc     178000.0     ASDASD    1.15
19    AAU          Phi Corp      89000.0    92000.0   -0.45
20    AAV           Chi Ltd     134000.0   130000.0    0.65
21    AAW           Psi Inc      67000.0    70000.0   -0.75
22    AAX        Omega Corp      45000.0    48000.0   -1.15
23    AAY     AlphaBeta Ltd     250000.0   230000.0    2.25
24    AAZ    GammaDelta Inc      99000.0   100000.0   -0.05
25    ABA  EpsilonZeta Corp     175000.0   160000.0    1.35
26    ABB      EtaTheta Ltd      88000.0    90000.0   -0.55
27    ABC     IotaKappa Inc     143500.0   140000.0    0.95
28    ABD     LambdaMu Corp     212000.0   200000.0    1.65
29    ABE          NuXi Ltd      66000.0    70000.0   -0.85
30    ABF     OmicronPi Inc       ASDASD   150000.0    0.55
31    ABG     RhoSigma Corp      87000.0    92000.0   -1.05
32    ABH    TauUpsilon Ltd      96000.0    94000.0    0.75
33    ABI        PhiChi Inc     118000.0   115000.0  ASDASD
34    ABJ     PsiOmega Corp     223000.0   210000.0    1.95
35    ABK      AlphaOne Ltd     178000.0   165000.0    1.25
36    ABL       BetaTwo Inc     134000.0   140000.0   -0.65
37    ABM   GammaThree Corp     198000.0   185000.0    1.55
38    ABN     DeltaFour Ltd      88000.0    92000.0   -0.95
39    ABO   EpsilonFive Inc      74000.0    76000.0   -0.35
40    ABP      ZetaSix Corp     120000.0   110000.0    1.05
41    ABQ      EtaSeven Ltd      99000.0   102000.0   -0.25
42    ABR    ThetaEight Inc      65000.0    70000.0  ASDASD
43    ABS     IotaNine Corp     205000.0   190000.0    2.05
44    ABT      KappaTen Ltd      87000.0    86000.0    0.35
45    ABU  LambdaEleven Inc     132000.0   125000.0    0.85
46    ABV     MuTwelve Corp     143000.0   150000.0   -0.75
47    ABW    NuThirteen Ltd       ASDASD    95000.0    0.55
48    ABX    XiFourteen Inc     158000.0   140000.0    1.75

In [6]:
var.fillna({"TODAY-VOLUME":"asdasd","AVG.VOLUME":"zxczxc","CHANGE":"rtyrty"})

   SYMBOL          SECURITY TODAY-VOLUME AVG.VOLUME  CHANGE
0     AAA        Alpha Corp     152300.0   140000.0    1.25
1     AAC         Gamma Inc      98500.0   102000.0    0.45
2     AAD         Delta PLC     305000.0   280000.0    2.15
3     AAE       Epsilon Ltd     120400.0     zxczxc   -1.05
4     AAF         Zeta Corp      87600.0    90000.0    0.75
5     AAG           Eta Inc      65400.0    70000.0   -0.55
6     AAH         Theta Ltd     450000.0   420000.0    3.25
7     AAI         Iota Corp     132000.0   128000.0    0.95
8     AAJ         Kappa Ltd       asdasd    80000.0   -0.35
9     AAK        Lambda Inc      54000.0    60000.0   -1.25
10    AAL           Mu Corp     221000.0   200000.0    1.75
11    AAM            Nu Ltd     310000.0   295000.0    2.05
12    AAN            Xi Inc     112000.0   120000.0   -0.65
13    AAO      Omicron Corp      99000.0    95000.0    0.55
14    AAP            Pi Ltd     185000.0   170000.0    1.45
15    AAQ           Rho Inc      76000.0    78000.0   -0.25
16    AAR        Sigma Corp     143000.0   135000.0    0.85
17    AAS           Tau Ltd     204000.0   210000.0   -0.95
18    AAT       Upsilon Inc     178000.0     zxczxc    1.15
19    AAU          Phi Corp      89000.0    92000.0   -0.45
20    AAV           Chi Ltd     134000.0   130000.0    0.65
21    AAW           Psi Inc      67000.0    70000.0   -0.75
22    AAX        Omega Corp      45000.0    48000.0   -1.15
23    AAY     AlphaBeta Ltd     250000.0   230000.0    2.25
24    AAZ    GammaDelta Inc      99000.0   100000.0   -0.05
25    ABA  EpsilonZeta Corp     175000.0   160000.0    1.35
26    ABB      EtaTheta Ltd      88000.0    90000.0   -0.55
27    ABC     IotaKappa Inc     143500.0   140000.0    0.95
28    ABD     LambdaMu Corp     212000.0   200000.0    1.65
29    ABE          NuXi Ltd      66000.0    70000.0   -0.85
30    ABF     OmicronPi Inc       asdasd   150000.0    0.55
31    ABG     RhoSigma Corp      87000.0    92000.0   -1.05
32    ABH    TauUpsilon Ltd      96000.0    94000.0    0.75
33    ABI        PhiChi Inc     118000.0   115000.0  rtyrty
34    ABJ     PsiOmega Corp     223000.0   210000.0    1.95
35    ABK      AlphaOne Ltd     178000.0   165000.0    1.25
36    ABL       BetaTwo Inc     134000.0   140000.0   -0.65
37    ABM   GammaThree Corp     198000.0   185000.0    1.55
38    ABN     DeltaFour Ltd      88000.0    92000.0   -0.95
39    ABO   EpsilonFive Inc      74000.0    76000.0   -0.35
40    ABP      ZetaSix Corp     120000.0   110000.0    1.05
41    ABQ      EtaSeven Ltd      99000.0   102000.0   -0.25
42    ABR    ThetaEight Inc      65000.0    70000.0  rtyrty
43    ABS     IotaNine Corp     205000.0   190000.0    2.05
44    ABT      KappaTen Ltd      87000.0    86000.0    0.35
45    ABU  LambdaEleven Inc     132000.0   125000.0    0.85
46    ABV     MuTwelve Corp     143000.0   150000.0   -0.75
47    ABW    NuThirteen Ltd       asdasd    95000.0    0.55
48    ABX    XiFourteen Inc     158000.0   140000.0    1.75