# GroupBy

In [1]:
import pandas as pd

In [3]:
var=pd.DataFrame({"name":['a','s','d','f','z','x','c','a','s','d','v'], "s1":[10,11,15,45,3,7,51,54,56,23,49], "s2":[33,15,6,48,75,78,24,65,95,13,57]})
var

   name  s1  s2
0     a  10  33
1     s  11  15
2     d  15   6
3     f  45  48
4     z   3  75
5     x   7  78
6     c  51  24
7     a  54  65
8     s  56  95
9     d  23  13
10    v  49  57

In [4]:
var_new=var.groupby("name")
var_new

In [6]:
for x,y in var_new:
    print(x)
    print(y)
    print()

a
  name  s1  s2
0    a  10  33
7    a  54  65

c
  name  s1  s2
6    c  51  24

d
  name  s1  s2
2    d  15   6
9    d  23  13

f
  name  s1  s2
3    f  45  48

s
  name  s1  s2
1    s  11  15
8    s  56  95

v
   name  s1  s2
10    v  49  57

x
  name  s1  s2
5    x   7  78

z
  name  s1  s2
4    z   3  75

In [7]:
# To get specific grouped key data
var_new.get_group("a")

  name  s1  s2
0    a  10  33
7    a  54  65

In [9]:
# Get min and max values from group
# var_new.min()
var_new.max()

      s1  s2
name
a     54  65
c     51  24
d     23  13
f     45  48
s     56  95
v     49  57
x      7  78
z      3  75

In [10]:
# Convert to the list
li=list(var_new)
li

[('a',
    name  s1  s2
  0    a  10  33
  7    a  54  65),
 ('c',
    name  s1  s2
  6    c  51  24),
 ('d',
    name  s1  s2
  2    d  15   6
  9    d  23  13),
 ('f',
    name  s1  s2
  3    f  45  48),
 ('s',
    name  s1  s2
  1    s  11  15
  8    s  56  95),
 ('v',
     name  s1  s2
  10    v  49  57),
 ('x',
    name  s1  s2
  5    x   7  78),
 ('z',
    name  s1  s2
  4    z   3  75)]