# Melt

In [1]:
import pandas as pd

In [5]:
v1=pd.DataFrame({"days":[1,2,3,4,5,6], "name":['a','b','c','d','a','b'], "eng":[12,17,18,10,13,14], "maths":[10,14,16,18,15,17]})
v1

   days name  eng  maths
0     1    a   12     10
1     2    b   17     14
2     3    c   18     16
3     4    d   10     18
4     5    a   13     15
5     6    b   14     17

In [6]:
pd.melt(v1)

   variable value
0      days     1
1      days     2
2      days     3
3      days     4
4      days     5
5      days     6
6      name     a
7      name     b
8      name     c
9      name     d
10     name     a
11     name     b
12      eng    12
13      eng    17
14      eng    18
15      eng    10
16      eng    13
17      eng    14
18    maths    10
19    maths    14
20    maths    16
21    maths    18
22    maths    15
23    maths    17

# Pivot

In [9]:
v1.pivot(columns=["name", "days"])

       eng                               maths
name     a     b     c     d     a     b     a     b     c     d     a     b
days     1     2     3     4     5     6     1     2     3     4     5     6
0     12.0   NaN   NaN   NaN   NaN   NaN  10.0   NaN   NaN   NaN   NaN   NaN
1      NaN  17.0   NaN   NaN   NaN   NaN   NaN  14.0   NaN   NaN   NaN   NaN
2      NaN   NaN  18.0   NaN   NaN   NaN   NaN   NaN  16.0   NaN   NaN   NaN
3      NaN   NaN   NaN  10.0   NaN   NaN   NaN   NaN   NaN  18.0   NaN   NaN
4      NaN   NaN   NaN   NaN  13.0   NaN   NaN   NaN   NaN   NaN  15.0   NaN
5      NaN   NaN   NaN   NaN   NaN  14.0   NaN   NaN   NaN   NaN   NaN  17.0