# Replace

In [25]:
import pandas as pd

In [26]:
var=pd.read_csv("sample.csv")
var

   SYMBOL          SECURITY  TODAY-VOLUME  AVG.VOLUME  CHANGE
0     AAA        Alpha Corp      152300.0    140000.0    1.25
1     AAB         Bison Ltd           NaN         NaN     NaN
2     AAC         Gamma Inc       98500.0    102000.0    0.45
3     AAD         Delta PLC      305000.0    280000.0    2.15
4     AAE       Epsilon Ltd      120400.0         NaN   -1.05
5     AAF         Zeta Corp       87600.0     90000.0    0.75
6     AAG           Eta Inc       65400.0     70000.0   -0.55
7     AAH         Theta Ltd      450000.0    420000.0    3.25
8     AAI         Iota Corp      132000.0    128000.0    0.95
9     AAJ         Kappa Ltd           NaN     80000.0   -0.35
10    AAK        Lambda Inc       54000.0     60000.0   -1.25
11    AAL           Mu Corp      221000.0    200000.0    1.75
12    AAM            Nu Ltd      310000.0    295000.0    2.05
13    AAN            Xi Inc      112000.0    120000.0   -0.65
14    AAO      Omicron Corp       99000.0     95000.0    0.55
15    AAP            Pi Ltd      185000.0    170000.0    1.45
16    AAQ           Rho Inc       76000.0     78000.0   -0.25
17    AAR        Sigma Corp      143000.0    135000.0    0.85
18    AAS           Tau Ltd      204000.0    210000.0   -0.95
19    AAT       Upsilon Inc      178000.0         NaN    1.15
20    AAU          Phi Corp       89000.0     92000.0   -0.45
21    AAV           Chi Ltd      134000.0    130000.0    0.65
22    AAW           Psi Inc       67000.0     70000.0   -0.75
23    AAX        Omega Corp       45000.0     48000.0   -1.15
24    AAY     AlphaBeta Ltd      250000.0    230000.0    2.25
25    AAZ    GammaDelta Inc       99000.0    100000.0   -0.05
26    ABA  EpsilonZeta Corp      175000.0    160000.0    1.35
27    ABB      EtaTheta Ltd       88000.0     90000.0   -0.55
28    ABC     IotaKappa Inc      143500.0    140000.0    0.95
29    ABD     LambdaMu Corp      212000.0    200000.0    1.65
30    ABE          NuXi Ltd       66000.0     70000.0   -0.85
31    ABF     OmicronPi Inc           NaN    150000.0    0.55
32    ABG     RhoSigma Corp       87000.0     92000.0   -1.05
33    ABH    TauUpsilon Ltd       96000.0     94000.0    0.75
34    ABI        PhiChi Inc      118000.0    115000.0     NaN
35    ABJ     PsiOmega Corp      223000.0    210000.0    1.95
36    ABK      AlphaOne Ltd      178000.0    165000.0    1.25
37    ABL       BetaTwo Inc      134000.0    140000.0   -0.65
38    ABM   GammaThree Corp      198000.0    185000.0    1.55
39    ABN     DeltaFour Ltd       88000.0     92000.0   -0.95
40    ABO   EpsilonFive Inc       74000.0     76000.0   -0.35
41    ABP      ZetaSix Corp      120000.0    110000.0    1.05
42    ABQ      EtaSeven Ltd       99000.0    102000.0   -0.25
43    ABR    ThetaEight Inc       65000.0     70000.0     NaN
44    ABS     IotaNine Corp      205000.0    190000.0    2.05
45    ABT      KappaTen Ltd       87000.0     86000.0    0.35
46    ABU  LambdaEleven Inc      132000.0    125000.0    0.85
47    ABV     MuTwelve Corp      143000.0    150000.0   -0.75
48    ABW    NuThirteen Ltd           NaN     95000.0    0.55
49    ABX    XiFourteen Inc      158000.0    140000.0    1.75

In [27]:
var.replace("Gamma Inc", "QWEQWE")

# Regex
# var.replace("[A-Za-Z]", "QWEQWE", regex=True)

# Using dictionary
# var.replace({"SECURITY":'[A-Z]'}, 22, regex=True)

   SYMBOL          SECURITY  TODAY-VOLUME  AVG.VOLUME  CHANGE
0     AAA        Alpha Corp      152300.0    140000.0    1.25
1     AAB         Bison Ltd           NaN         NaN     NaN
2     AAC            QWEQWE       98500.0    102000.0    0.45
3     AAD         Delta PLC      305000.0    280000.0    2.15
4     AAE       Epsilon Ltd      120400.0         NaN   -1.05
5     AAF         Zeta Corp       87600.0     90000.0    0.75
6     AAG           Eta Inc       65400.0     70000.0   -0.55
7     AAH         Theta Ltd      450000.0    420000.0    3.25
8     AAI         Iota Corp      132000.0    128000.0    0.95
9     AAJ         Kappa Ltd           NaN     80000.0   -0.35
10    AAK        Lambda Inc       54000.0     60000.0   -1.25
11    AAL           Mu Corp      221000.0    200000.0    1.75
12    AAM            Nu Ltd      310000.0    295000.0    2.05
13    AAN            Xi Inc      112000.0    120000.0   -0.65
14    AAO      Omicron Corp       99000.0     95000.0    0.55
15    AAP            Pi Ltd      185000.0    170000.0    1.45
16    AAQ           Rho Inc       76000.0     78000.0   -0.25
17    AAR        Sigma Corp      143000.0    135000.0    0.85
18    AAS           Tau Ltd      204000.0    210000.0   -0.95
19    AAT       Upsilon Inc      178000.0         NaN    1.15
20    AAU          Phi Corp       89000.0     92000.0   -0.45
21    AAV           Chi Ltd      134000.0    130000.0    0.65
22    AAW           Psi Inc       67000.0     70000.0   -0.75
23    AAX        Omega Corp       45000.0     48000.0   -1.15
24    AAY     AlphaBeta Ltd      250000.0    230000.0    2.25
25    AAZ    GammaDelta Inc       99000.0    100000.0   -0.05
26    ABA  EpsilonZeta Corp      175000.0    160000.0    1.35
27    ABB      EtaTheta Ltd       88000.0     90000.0   -0.55
28    ABC     IotaKappa Inc      143500.0    140000.0    0.95
29    ABD     LambdaMu Corp      212000.0    200000.0    1.65
30    ABE          NuXi Ltd       66000.0     70000.0   -0.85
31    ABF     OmicronPi Inc           NaN    150000.0    0.55
32    ABG     RhoSigma Corp       87000.0     92000.0   -1.05
33    ABH    TauUpsilon Ltd       96000.0     94000.0    0.75
34    ABI        PhiChi Inc      118000.0    115000.0     NaN
35    ABJ     PsiOmega Corp      223000.0    210000.0    1.95
36    ABK      AlphaOne Ltd      178000.0    165000.0    1.25
37    ABL       BetaTwo Inc      134000.0    140000.0   -0.65
38    ABM   GammaThree Corp      198000.0    185000.0    1.55
39    ABN     DeltaFour Ltd       88000.0     92000.0   -0.95
40    ABO   EpsilonFive Inc       74000.0     76000.0   -0.35
41    ABP      ZetaSix Corp      120000.0    110000.0    1.05
42    ABQ      EtaSeven Ltd       99000.0    102000.0   -0.25
43    ABR    ThetaEight Inc       65000.0     70000.0     NaN
44    ABS     IotaNine Corp      205000.0    190000.0    2.05
45    ABT      KappaTen Ltd       87000.0     86000.0    0.35
46    ABU  LambdaEleven Inc      132000.0    125000.0    0.85
47    ABV     MuTwelve Corp      143000.0    150000.0   -0.75
48    ABW    NuThirteen Ltd           NaN     95000.0    0.55
49    ABX    XiFourteen Inc      158000.0    140000.0    1.75

In [28]:
# inplace: to make modification in original dataset, not in copy
var.replace("Alpha Corp", "ASDASDASDASDASD", inplace=True)

   SYMBOL          SECURITY  TODAY-VOLUME  AVG.VOLUME  CHANGE
0     AAA   ASDASDASDASDASD      152300.0    140000.0    1.25
1     AAB         Bison Ltd           NaN         NaN     NaN
2     AAC         Gamma Inc       98500.0    102000.0    0.45
3     AAD         Delta PLC      305000.0    280000.0    2.15
4     AAE       Epsilon Ltd      120400.0         NaN   -1.05
5     AAF         Zeta Corp       87600.0     90000.0    0.75
6     AAG           Eta Inc       65400.0     70000.0   -0.55
7     AAH         Theta Ltd      450000.0    420000.0    3.25
8     AAI         Iota Corp      132000.0    128000.0    0.95
9     AAJ         Kappa Ltd           NaN     80000.0   -0.35
10    AAK        Lambda Inc       54000.0     60000.0   -1.25
11    AAL           Mu Corp      221000.0    200000.0    1.75
12    AAM            Nu Ltd      310000.0    295000.0    2.05
13    AAN            Xi Inc      112000.0    120000.0   -0.65
14    AAO      Omicron Corp       99000.0     95000.0    0.55
15    AAP            Pi Ltd      185000.0    170000.0    1.45
16    AAQ           Rho Inc       76000.0     78000.0   -0.25
17    AAR        Sigma Corp      143000.0    135000.0    0.85
18    AAS           Tau Ltd      204000.0    210000.0   -0.95
19    AAT       Upsilon Inc      178000.0         NaN    1.15
20    AAU          Phi Corp       89000.0     92000.0   -0.45
21    AAV           Chi Ltd      134000.0    130000.0    0.65
22    AAW           Psi Inc       67000.0     70000.0   -0.75
23    AAX        Omega Corp       45000.0     48000.0   -1.15
24    AAY     AlphaBeta Ltd      250000.0    230000.0    2.25
25    AAZ    GammaDelta Inc       99000.0    100000.0   -0.05
26    ABA  EpsilonZeta Corp      175000.0    160000.0    1.35
27    ABB      EtaTheta Ltd       88000.0     90000.0   -0.55
28    ABC     IotaKappa Inc      143500.0    140000.0    0.95
29    ABD     LambdaMu Corp      212000.0    200000.0    1.65
30    ABE          NuXi Ltd       66000.0     70000.0   -0.85
31    ABF     OmicronPi Inc           NaN    150000.0    0.55
32    ABG     RhoSigma Corp       87000.0     92000.0   -1.05
33    ABH    TauUpsilon Ltd       96000.0     94000.0    0.75
34    ABI        PhiChi Inc      118000.0    115000.0     NaN
35    ABJ     PsiOmega Corp      223000.0    210000.0    1.95
36    ABK      AlphaOne Ltd      178000.0    165000.0    1.25
37    ABL       BetaTwo Inc      134000.0    140000.0   -0.65
38    ABM   GammaThree Corp      198000.0    185000.0    1.55
39    ABN     DeltaFour Ltd       88000.0     92000.0   -0.95
40    ABO   EpsilonFive Inc       74000.0     76000.0   -0.35
41    ABP      ZetaSix Corp      120000.0    110000.0    1.05
42    ABQ      EtaSeven Ltd       99000.0    102000.0   -0.25
43    ABR    ThetaEight Inc       65000.0     70000.0     NaN
44    ABS     IotaNine Corp      205000.0    190000.0    2.05
45    ABT      KappaTen Ltd       87000.0     86000.0    0.35
46    ABU  LambdaEleven Inc      132000.0    125000.0    0.85
47    ABV     MuTwelve Corp      143000.0    150000.0   -0.75
48    ABW    NuThirteen Ltd           NaN     95000.0    0.55
49    ABX    XiFourteen Inc      158000.0    140000.0    1.75

# Interpolate

In [46]:
var=pd.read_csv("sample.csv")
var

   SYMBOL          SECURITY  TODAY-VOLUME  AVG.VOLUME  CHANGE
0     AAA        Alpha Corp      152300.0    140000.0    1.25
1     AAB         Bison Ltd           NaN         NaN     NaN
2     AAC         Gamma Inc       98500.0    102000.0    0.45
3     AAD         Delta PLC      305000.0    280000.0    2.15
4     AAE       Epsilon Ltd      120400.0         NaN   -1.05
5     AAF         Zeta Corp       87600.0     90000.0    0.75
6     AAG           Eta Inc       65400.0     70000.0   -0.55
7     AAH         Theta Ltd      450000.0    420000.0    3.25
8     AAI         Iota Corp      132000.0    128000.0    0.95
9     AAJ         Kappa Ltd           NaN     80000.0   -0.35
10    AAK        Lambda Inc       54000.0     60000.0   -1.25
11    AAL           Mu Corp      221000.0    200000.0    1.75
12    AAM            Nu Ltd      310000.0    295000.0    2.05
13    AAN            Xi Inc      112000.0    120000.0   -0.65
14    AAO      Omicron Corp       99000.0     95000.0    0.55
15    AAP            Pi Ltd      185000.0    170000.0    1.45
16    AAQ           Rho Inc       76000.0     78000.0   -0.25
17    AAR        Sigma Corp      143000.0    135000.0    0.85
18    AAS           Tau Ltd      204000.0    210000.0   -0.95
19    AAT       Upsilon Inc      178000.0         NaN    1.15
20    AAU          Phi Corp       89000.0     92000.0   -0.45
21    AAV           Chi Ltd      134000.0    130000.0    0.65
22    AAW           Psi Inc       67000.0     70000.0   -0.75
23    AAX        Omega Corp       45000.0     48000.0   -1.15
24    AAY     AlphaBeta Ltd      250000.0    230000.0    2.25
25    AAZ    GammaDelta Inc       99000.0    100000.0   -0.05
26    ABA  EpsilonZeta Corp      175000.0    160000.0    1.35
27    ABB      EtaTheta Ltd       88000.0     90000.0   -0.55
28    ABC     IotaKappa Inc      143500.0    140000.0    0.95
29    ABD     LambdaMu Corp      212000.0    200000.0    1.65
30    ABE          NuXi Ltd       66000.0     70000.0   -0.85
31    ABF     OmicronPi Inc           NaN    150000.0    0.55
32    ABG     RhoSigma Corp       87000.0     92000.0   -1.05
33    ABH    TauUpsilon Ltd       96000.0     94000.0    0.75
34    ABI        PhiChi Inc      118000.0    115000.0     NaN
35    ABJ     PsiOmega Corp      223000.0    210000.0    1.95
36    ABK      AlphaOne Ltd      178000.0    165000.0    1.25
37    ABL       BetaTwo Inc      134000.0    140000.0   -0.65
38    ABM   GammaThree Corp      198000.0    185000.0    1.55
39    ABN     DeltaFour Ltd       88000.0     92000.0   -0.95
40    ABO   EpsilonFive Inc       74000.0     76000.0   -0.35
41    ABP      ZetaSix Corp      120000.0    110000.0    1.05
42    ABQ      EtaSeven Ltd       99000.0    102000.0   -0.25
43    ABR    ThetaEight Inc       65000.0     70000.0     NaN
44    ABS     IotaNine Corp      205000.0    190000.0    2.05
45    ABT      KappaTen Ltd       87000.0     86000.0    0.35
46    ABU  LambdaEleven Inc      132000.0    125000.0    0.85
47    ABV     MuTwelve Corp      143000.0    150000.0   -0.75
48    ABW    NuThirteen Ltd           NaN     95000.0    0.55
49    ABX    XiFourteen Inc      158000.0    140000.0    1.75

In [47]:
# List the columns that contain numbers
numeric_cols = ['TODAY-VOLUME', 'AVG.VOLUME', 'CHANGE']

# Interpolate only those columns
var[numeric_cols] = var[numeric_cols].interpolate()
var

   SYMBOL          SECURITY  TODAY-VOLUME  AVG.VOLUME  CHANGE
0     AAA        Alpha Corp      152300.0    140000.0    1.25
1     AAB         Bison Ltd      125400.0    121000.0    0.85
2     AAC         Gamma Inc       98500.0    102000.0    0.45
3     AAD         Delta PLC      305000.0    280000.0    2.15
4     AAE       Epsilon Ltd      120400.0    185000.0   -1.05
5     AAF         Zeta Corp       87600.0     90000.0    0.75
6     AAG           Eta Inc       65400.0     70000.0   -0.55
7     AAH         Theta Ltd      450000.0    420000.0    3.25
8     AAI         Iota Corp      132000.0    128000.0    0.95
9     AAJ         Kappa Ltd       93000.0     80000.0   -0.35
10    AAK        Lambda Inc       54000.0     60000.0   -1.25
11    AAL           Mu Corp      221000.0    200000.0    1.75
12    AAM            Nu Ltd      310000.0    295000.0    2.05
13    AAN            Xi Inc      112000.0    120000.0   -0.65
14    AAO      Omicron Corp       99000.0     95000.0    0.55
15    AAP            Pi Ltd      185000.0    170000.0    1.45
16    AAQ           Rho Inc       76000.0     78000.0   -0.25
17    AAR        Sigma Corp      143000.0    135000.0    0.85
18    AAS           Tau Ltd      204000.0    210000.0   -0.95
19    AAT       Upsilon Inc      178000.0    151000.0    1.15
20    AAU          Phi Corp       89000.0     92000.0   -0.45
21    AAV           Chi Ltd      134000.0    130000.0    0.65
22    AAW           Psi Inc       67000.0     70000.0   -0.75
23    AAX        Omega Corp       45000.0     48000.0   -1.15
24    AAY     AlphaBeta Ltd      250000.0    230000.0    2.25
25    AAZ    GammaDelta Inc       99000.0    100000.0   -0.05
26    ABA  EpsilonZeta Corp      175000.0    160000.0    1.35
27    ABB      EtaTheta Ltd       88000.0     90000.0   -0.55
28    ABC     IotaKappa Inc      143500.0    140000.0    0.95
29    ABD     LambdaMu Corp      212000.0    200000.0    1.65
30    ABE          NuXi Ltd       66000.0     70000.0   -0.85
31    ABF     OmicronPi Inc       76500.0    150000.0    0.55
32    ABG     RhoSigma Corp       87000.0     92000.0   -1.05
33    ABH    TauUpsilon Ltd       96000.0     94000.0    0.75
34    ABI        PhiChi Inc      118000.0    115000.0    1.35
35    ABJ     PsiOmega Corp      223000.0    210000.0    1.95
36    ABK      AlphaOne Ltd      178000.0    165000.0    1.25
37    ABL       BetaTwo Inc      134000.0    140000.0   -0.65
38    ABM   GammaThree Corp      198000.0    185000.0    1.55
39    ABN     DeltaFour Ltd       88000.0     92000.0   -0.95
40    ABO   EpsilonFive Inc       74000.0     76000.0   -0.35
41    ABP      ZetaSix Corp      120000.0    110000.0    1.05
42    ABQ      EtaSeven Ltd       99000.0    102000.0   -0.25
43    ABR    ThetaEight Inc       65000.0     70000.0    0.90
44    ABS     IotaNine Corp      205000.0    190000.0    2.05
45    ABT      KappaTen Ltd       87000.0     86000.0    0.35
46    ABU  LambdaEleven Inc      132000.0    125000.0    0.85
47    ABV     MuTwelve Corp      143000.0    150000.0   -0.75
48    ABW    NuThirteen Ltd      150500.0     95000.0    0.55
49    ABX    XiFourteen Inc      158000.0    140000.0    1.75