# Creating Series

In [65]:
import pandas as pd

In [66]:
a=pd.Series([1,2,3], index=['a','b','c'])
a

a    1
b    2
c    3
dtype: int64

In [67]:
pd.Series({1:10,2:20,3:30})

1    10
2    20
3    30
dtype: int64

# Creating Dataframes

In [68]:
data={
    'name':['John','Anna','Peter','Linda'],
    'age':[28,34,29,42],
    'city':['New York','Paris','Berlin','London'],
    'salary':[65000,70000,62000,85000]
}
df=pd.DataFrame(data)
df

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [69]:
data_list=[
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2=pd.DataFrame(data_list)
custom_columns=["Name", "Age", "City", "Salary"]
df2=pd.DataFrame(data_list, columns=custom_columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### Selection and indexing of columns

In [70]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [71]:
df2[["Name",'Salary']]

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

### Creating a new column

In [72]:
df2["Designation"]=["Doctor","Engineer","Driver","Minister"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Driver
3  Linda   42    London   85000    Minister

### Removing columns

In [73]:
# By default axis=0(row). 'inplace' is used to make changes in actual data in memory
df2.drop("Designation",axis=1, inplace=True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [74]:
df2.drop([2,3],axis=0)

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

### Selecting Rows

In [75]:
# use 'loc' to select rows
df2.loc[[1,2]]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000

In [76]:
# use 'iloc' for indexed location
df2.iloc[[2,3]]

    Name  Age    City  Salary
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

### Selecting subsets of Rows and Columns

In [77]:
df

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [78]:
df.loc[list(range(1, 4, 2)), ['city', 'salary']]

     city  salary
1   Paris   70000
3  London   85000

### Conditional Selection

In [79]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [80]:
# Get only those who are above 30
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [81]:
# Get only those who are above 30 and from Paris
df2[(df2["Age"]>30) & (df2["City"]=="Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000